# Generated by Django 4.1.2 on 2022-10-29 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song', to='musicapp.artiste'),
        ),
        migrations.DeleteModel(
            name='Lyric',
        ),
        migrations.AddField(
            model_name='lyrics',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='musicapp.song'),
        ),
    ]
