# Generated by Django 4.1.2 on 2022-10-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_lyrics_alter_song_artiste_id_delete_lyric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(),
        ),
    ]
